# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

# Base URL
baseurl:

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title:

description: Stylish Jekyll Theme
author:
  name: charalampos karypidis
  email: xaralaboskaripidis@gmail.com
  github: xabikos
  twitter: xabikos
  pinterest:
  linkedin: charalamposkarypidis
  bio: Life runs on code
  email_md5:

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
