# Harmony Jekyll theme general configurations 

# Base URL
baseurl: 

# Site live URL
url: http://xabikos.com

# Localhost 
#url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: xabikos
  # Little description about your site
  description:
  meta_description: This is Charalampos Karypidis technical blog. It contains information about software development with Microsoft Technologies (.NET, Windows Azure, Azure web sites)
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Charalampos Karypidis
    email: xaralaboskaripidis@gmail.com
    url: http://xabikos.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key:

  # Profile links, leave blank to ignore
  social: 
    github: xabikos
    twitter: xabikos
    facebook:
    gplus:
    dribble:
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: false
  show_download_link: false

# Conversion / Build settings 
markdown:    kramdown
highlighter: null

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
